name: C CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install clang-format
      run: sudo apt install clang-format-6.0
    - name: Build from source
      run: make ycc
    - name: Run test
      run: make test
